from pydantic import BaseModel, Field
from typing import List, Optional

class LogBatchRequest(BaseModel):
    log_batch: List[str] = Field(..., description="List of raw log lines to analyze.")

class AnalysisResult(BaseModel):
    blocked: bool = Field(..., description="True if a prompt injection was detected and blocked.")
    technique_id: Optional[str] = Field(None, description="The MITRE ATT&CK technique ID identified, if any.")
    hypothesis: Optional[str] = Field(None, description="The threat hunting hypothesis generated by the LLM.")
    confidence: Optional[float] = Field(None, description="Confidence score from the hallucination scorer (0.0 to 1.0).")

class LogBatchResponse(BaseModel):
    results: List[AnalysisResult] = Field(..., description="Analysis results for each log in the batch.")
